name: "CI"
on: 
  pull_request:
    branches:
    - master
  push:
jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      uses: actions/setup-node@v2
      with:
          node-version: '12'
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install
      - run: yarn test