name: "CI"
on: 
  pull_request:
    branches: [ master ]
  push:
    branches: [ dev ]
jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn test